{% set name = "jaraco.text" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 901d3468eaaa04f1d8a8f141f54b8887bfd943ccba311fc1c1de62c66604dfe0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=3.4.1
  run:
    - python >=3.6
    - jaraco.functools
    - importlib_resources  # [py<39]

test:
  imports:
    - jaraco.text

about:
  home: https://github.com/jaraco/jaraco.text
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Module for text manipulation
  doc_url: https://jaracotext.readthedocs.io/
  dev_url: https://github.com/jaraco/jaraco.text

extra:
  recipe-maintainers:
    - carlodri
