{% set name = "jaraco.text" %}
{% set version = "3.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 333a5df2148f7139718607cdf352fe1d95162971a7299c380dcc24dab0168980

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm >=3.4.1
  run:
    - python
    - jaraco.functools
    - jaraco.context >=4.1
    - importlib_resources  # [py<39]
    - autocommand
    - inflect

test:
  imports:
    - jaraco.text

about:
  home: https://github.com/jaraco/jaraco.text
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Module for text manipulation
  doc_url: https://jaracotext.readthedocs.io/
  dev_url: https://github.com/jaraco/jaraco.text

extra:
  recipe-maintainers:
    - carlodri
