{% set name = "jaraco.text" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaraco_text-{{ version }}.tar.gz
  sha256: 5b71fecea69ab6f939d4c906c04fee1eda76500d1641117df6ec45b865f10db0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
    - setuptools_scm >=3.4.1
  run:
    - python
    - jaraco.functools
    - jaraco.context >=4.1
    - importlib_resources  # [py<39]
    - autocommand
    - inflect
    - more-itertools

test:
  imports:
    - jaraco.text

about:
  home: https://github.com/jaraco/jaraco.text
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Module for text manipulation
  doc_url: https://jaracotext.readthedocs.io/
  dev_url: https://github.com/jaraco/jaraco.text

extra:
  recipe-maintainers:
    - carlodri
